git:
  depth: 5
stages:
  - "Build and Test"
  - "Package"
jobs:
  include:
    - stage: "Build and Test"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
      script:
        - echo "Maven build"
        - echo "Run test coverage and Quality Gate"
        - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marouanedev
      addons:
        sonarcloud:
          organization: "marouanedev"
          token: "$SONARCLOUD_TOKEN"
    - stage: "Build and Test"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "NPM install and build"
    - stage: "Package"
      if: branch = develop
      before_script:
        - cd sample-application-backend
      script:
        - echo "Docker build ..."
        - docker build -t $DOCKER_ID/backend .
        - echo "Docker login ..."
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - echo "Docker push ..."
        - docker push $DOCKER_ID/backend
    - stage: "Package"
      if: branch = develop
      before_script:
        - cd sample-application-frontend
      script:
        - echo "Docker build ..."
        - docker build -t $DOCKER_ID/frontend .
        - echo "Docker login ..."
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - echo "Docker push ..."
        - docker push $DOCKER_ID/frontend
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"

services:
  - docker